stages:
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKERHUB_USERNAME/crypto-price-predictor:latest .

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push $DOCKERHUB_USERNAME/crypto-price-predictor:latest

deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $EC2_IP >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa ubuntu@$EC2_IP '
        docker pull $DOCKERHUB_USERNAME/crypto-price-predictor:latest &&
        docker stop $(docker ps -q --filter ancestor=$DOCKERHUB_USERNAME/crypto-price-predictor:latest) || true &&
        docker run -d -p 80:8000 $DOCKERHUB_USERNAME/crypto-price-predictor:latest
      '
