stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

before_script:
  # This ensures Docker is logged in before any job runs
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin || true

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t pes1ug19cs098/crypto-price-predictor:latest .

push_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push pes1ug19cs098/crypto-price-predictor:latest
