import requests
import pandas as pd

def fetch_crypto_data(days=30):
    url = f"https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"
    params = {
        "vs_currency": "usd",
        "days": days,
        "interval": "daily"
    }
    response = requests.get(url, params=params).json()
    prices = response["prices"]
    df = pd.DataFrame(prices, columns=["timestamp", "price"])
    df["price"] = df["price"].astype(float)
    
    # --- New Feature Engineering Code Start ---
    # Convert timestamp from milliseconds to datetime
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    # Sort the data by timestamp
    df.sort_values('timestamp', inplace=True)
    # Create additional features
    df['MA_7'] = df['price'].rolling(window=7).mean()
    df['MA_30'] = df['price'].rolling(window=30).mean()
    df['Daily_Return'] = df['price'].pct_change()
    df['Volatility_7'] = df['Daily_Return'].rolling(window=7).std()
    # Remove rows with NaN values generated by rolling calculations
    df.dropna(inplace=True)
    # --- New Feature Engineering Code End ---
    
    return df
